name: 버그 신고
description: 동작/오류 제보
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: 어떤 문제가 있었나요?
      placeholder: 기대 동작과 실제 동작을 비교해서 적어주세요.
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: 재현 방법
      placeholder: 재현 단계(파일/버튼/로그 등)
  - type: input
    id: version
    attributes:
      label: 버전/커밋 해시
  - type: textarea
    id: logs
    attributes:
      label: 관련 로그/스크린샷
